### PR TITLE
Grd 643

### PR DESCRIPTION
**Pull request by hannahdriver**

### CODE REVIEW

**Review by gavin-peng — APPROVED** [review]
Looks good!

**Comment by bibilujan** [comment]
Looks good, just a few comments to improve the metadata.

**Comment by bibilujan** [comment]
copying my comments here, as the inline comments don't show up for Hannah. 
wdl line 309 small typo.
wdl line 308 onwards, please update the bam metadata based on the consensus cruncher repo: 
https://github.com/pughlab/ConsensusCruncher
```
.                                           Filetype
├── sscs
│   ├── badReads.bam                        Reads that are unmapped or have multiple alignments
│   ├── sscs.sorted.bam                     Single-Strand Consensus Sequences (SSCS)
│   ├── singleton.sorted.bam                Single reads (Singleton) that cannot form SSCSs
├── sscs_SC
|   ├── singleton.rescue.sorted.bam         Singleton correction (SC) with complementary singletons
|   ├── sscs.rescue.sorted.bam              SC with complementary SSCSs
|   ├── sscs.sc.sorted.bam                  SSCS combined with corrected singletons (from both rescue strategies)   [*]
|   ├── rescue.remaining.sorted.bam         Singletons that could not be corrected
|   ├── all.unique.sscs.sorted.bam          SSCS + SC + remaining (uncorrected) singletons
├── dcs
│   ├── dcs.sorted.bam                      Duplex Consensus Sequence (DCS)
│   ├── sscs.singleton.sorted.bam           SSCSs that could not form DCSs as complementary strand was missing  
├── dcs_SC
│   ├── dcs.sc.sorted.bam                   DCS generated from SSCS + SC    [*]
│   ├── sscs.sc.singleton.sorted.bam        SSCS + SC that could not form DCSs 
│   ├── all.unique.dcs.sorted.bam           DCS (from SSCS + SC) + SSCS_SC_Singletons + remaining singletons
├── read_families.txt                       Family size and frequency
├── stats.txt                               Consensus sequence formation metrics
├── tag_fam_size.png                        Distribution of reads across family size
└── time_tracker.txt      
```

**Comment by hannahdriver** [comment]
> copying my comments here, as the inline comments don't show up for Hannah. wdl line 309 small typo. wdl line 308 onwards, please update the bam metadata based on the consensus cruncher repo: https://github.com/pughlab/ConsensusCruncher
> 
> ```
> .                                           Filetype
> ├── sscs
> │   ├── badReads.bam                        Reads that are unmapped or have multiple alignments
> │   ├── sscs.sorted.bam                     Single-Strand Consensus Sequences (SSCS)
> │   ├── singleton.sorted.bam                Single reads (Singleton) that cannot form SSCSs
> ├── sscs_SC
> |   ├── singleton.rescue.sorted.bam         Singleton correction (SC) with complementary singletons
> |   ├── sscs.rescue.sorted.bam              SC with complementary SSCSs
> |   ├── sscs.sc.sorted.bam                  SSCS combined with corrected singletons (from both rescue strategies)   [*]
> |   ├── rescue.remaining.sorted.bam         Singletons that could not be corrected
> |   ├── all.unique.sscs.sorted.bam          SSCS + SC + remaining (uncorrected) singletons
> ├── dcs
> │   ├── dcs.sorted.bam                      Duplex Consensus Sequence (DCS)
> │   ├── sscs.singleton.sorted.bam           SSCSs that could not form DCSs as complementary strand was missing  
> ├── dcs_SC
> │   ├── dcs.sc.sorted.bam                   DCS generated from SSCS + SC    [*]
> │   ├── sscs.sc.singleton.sorted.bam        SSCS + SC that could not form DCSs 
> │   ├── all.unique.dcs.sorted.bam           DCS (from SSCS + SC) + SSCS_SC_Singletons + remaining singletons
> ├── read_families.txt                       Family size and frequency
> ├── stats.txt                               Consensus sequence formation metrics
> ├── tag_fam_size.png                        Distribution of reads across family size
> └── time_tracker.txt      
> ```

Thanks! I made some updates to the metadata - please let me know if anything looks wrong!

**Comment by bibilujan** [comment]
Metadata updates look good.

Why are we updating https://github.com/oicr-gsi/consensusCruncherWorkflow/blob/4a64f23e0321ac71e43ce0ef95618c7dc682d1c0/consensusCruncherWorkflow.wdl#L557 to be specified in the workflow? 
This was originally in the olive.

**Comment by bibilujan** [comment]
On the comment above, I believe it can still be specified in the olive, but this would now have a default value.

**Comment by hannahdriver** [comment]
> Metadata updates look good.
> 
> Why are we updating
> 
> https://github.com/oicr-gsi/consensusCruncherWorkflow/blob/4a64f23e0321ac71e43ce0ef95618c7dc682d1c0/consensusCruncherWorkflow.wdl#L557
> 
> to be specified in the workflow?
> This was originally in the olive.

@gavin-peng I believe you originally made this edit. Do you know why this was updated?

**Pull request merged**
